modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/EnvyWare/PixelHuntRemastered/issues"

[[mods]]
modId="pixelhuntremastered"
version="3.2.2"
displayName="PixelHuntRemastered Forge"
displayURL="https://github.com/EnvyWare"
credits="https://github.com/EnvyWare"
authors="https://github.com/EnvyWare"
updateJSONURL="https://ogn.pixelmonmod.com/update/sm-ph/update.json"
description='''
Adds PixelHunt
'''

[[dependencies.pixelhuntremastered]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.pixelhuntremastered]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"